apiVersion: v1
kind: Service
metadata:
  name: songs-generator
  labels:
    app: songs-generator
    component: songs-generator
    type: streaming-spike
    spring-deployment-id: songs-generator
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: songs-generator
      targetPort: 8080
      protocol: TCP

  selector:
    app: songs-generator
    component: songs-generator