apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
    component: rabbitmq-broker
    type: streaming-spike
spec:
  ports:
    - port: 5672
      targetPort: 5672
      protocol: TCP
      name: rabbitmq-port
    - port: 15672
      targetPort: 15672
      protocol: TCP
      name: rabbitmq-mgmt-port
  selector:
    app: rabbitmq
    component: rabbitmq-broker