apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-broker
  labels:
    app: rabbitmq
    type: streaming-spike
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
        component: rabbitmq-broker
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 15672
            - containerPort: 5672