apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
    component: kafka-broker
    type: streaming-spike
spec:
  ports:
    - port: 9092
      name: kafka-port
      targetPort: 9092
      protocol: TCP
    - port: 9094
      name: external-kafka-port
      targetPort: 9094
      protocol: TCP
  type: NodePort
  selector:
    app: kafka
    component: kafka-broker
